#Docker Image
From openJDK:11
LABEL maintainer="princekr1807@gmail.com"
EXPOSE 8080
COPY build/libs/patient-0.0.1-SNAPSHOT-plain.jar patient-0.0.1.jar
ENTRYPOINT ["java", "-jar", "/patient-0.0.1.jar"]